//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mo3RegUI.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mo3RegUI.LocalizationResources.TextResource", typeof(TextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current ANSI Code Page: {0}.
        /// </summary>
        public static string BasicInfoTask_CurrentAnsiCodePage {
            get {
                return ResourceManager.GetString("BasicInfoTask_CurrentAnsiCodePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check System Basic Info.
        /// </summary>
        public static string BasicInfoTask_Description {
            get {
                return ResourceManager.GetString("BasicInfoTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System: {0} {1}.
        /// </summary>
        public static string BasicInfoTask_OperatingSystem {
            get {
                return ResourceManager.GetString("BasicInfoTask_OperatingSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Memory: Total: {0:0.##} GB, Available: {1:0.##} GB.
        /// </summary>
        public static string BasicInfoTask_PhysicalMemory {
            get {
                return ResourceManager.GetString("BasicInfoTask_PhysicalMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Discord.
        /// </summary>
        public static string ChinaNetworkTask_Description {
            get {
                return ResourceManager.GetString("ChinaNetworkTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord has been successfully disabled..
        /// </summary>
        public static string ChinaNetworkTask_DiscordDisabled {
            get {
                return ResourceManager.GetString("ChinaNetworkTask_DiscordDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord is not disabled..
        /// </summary>
        public static string ChinaNetworkTask_DiscordNotDisabled {
            get {
                return ResourceManager.GetString("ChinaNetworkTask_DiscordNotDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Program Compatibility.
        /// </summary>
        public static string CompatibilitySettingTask_Description {
            get {
                return ResourceManager.GetString("CompatibilitySettingTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for Mental Omega 3.3.7.
        /// </summary>
        public static string Constants_AppName {
            get {
                return ResourceManager.GetString("Constants_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SadPencil.
        /// </summary>
        public static string Constants_AuthorName {
            get {
                return ResourceManager.GetString("Constants_AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mental Omega 3.3.7.
        /// </summary>
        public static string Constants_GameName {
            get {
                return ResourceManager.GetString("Constants_GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully added {0} to ExcludeFromKnownDlls..
        /// </summary>
        public static string DDrawDLLTask_AddedToExcludeFromKnownDlls {
            get {
                return ResourceManager.GetString("DDrawDLLTask_AddedToExcludeFromKnownDlls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Renderer Registry Entry.
        /// </summary>
        public static string DDrawDLLTask_Description {
            get {
                return ResourceManager.GetString("DDrawDLLTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcludeFromKnownDlls should be of type {0}, but is actually of type {1}..
        /// </summary>
        public static string DDrawDLLTask_ExcludeFromKnownDllsWrongType {
            get {
                return ResourceManager.GetString("DDrawDLLTask_ExcludeFromKnownDllsWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} registry entry is abnormal. {0} should not be in KnownDLLs..
        /// </summary>
        public static string DDrawDLLTask_RegistryEntryAbnormal {
            get {
                return ResourceManager.GetString("DDrawDLLTask_RegistryEntryAbnormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} registry entry is normal..
        /// </summary>
        public static string DDrawDLLTask_RegistryEntryNormal {
            get {
                return ResourceManager.GetString("DDrawDLLTask_RegistryEntryNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check DirectX Runtime (June 2010).
        /// </summary>
        public static string DirectXRuntimeTask_Description {
            get {
                return ResourceManager.GetString("DirectXRuntimeTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DirectX runtime components are not installed. File {0} not found. Please install DirectX End-User Runtimes (June 2010)..
        /// </summary>
        public static string DirectXRuntimeTask_NotInstalled {
            get {
                return ResourceManager.GetString("DirectXRuntimeTask_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check System ANSI Code Page.
        /// </summary>
        public static string EncodingCheckTask_Description {
            get {
                return ResourceManager.GetString("EncodingCheckTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current ANSI code page is UTF-8. This is a good practice, but unfortunately, non-English characters cannot be entered normally in the Red Alert 2 game, and components such as the map editor cannot fully display names containing non-English characters. In addition, this is one of the factors that affects whether button misalignment and overlapping issues appear in the game menu interface under high DPI..
        /// </summary>
        public static string EncodingCheckTask_Utf8Warning {
            get {
                return ResourceManager.GetString("EncodingCheckTask_Utf8Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Game Files (Rough).
        /// </summary>
        public static string FalsePositiveTask_Description {
            get {
                return ResourceManager.GetString("FalsePositiveTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game files are incomplete. File {0} not found. Please check your antivirus software log, add the game directory to the antivirus software whitelist, or replace other antivirus software, and then reinstall the game..
        /// </summary>
        public static string FalsePositiveTask_FileNotFound {
            get {
                return ResourceManager.GetString("FalsePositiveTask_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Firewall Exception.
        /// </summary>
        public static string FirewallSettingTask_Description {
            get {
                return ResourceManager.GetString("FirewallSettingTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows version is too low. Please set Windows Firewall manually..
        /// </summary>
        public static string FirewallSettingTask_OsVersionTooLow {
            get {
                return ResourceManager.GetString("FirewallSettingTask_OsVersionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss First Run Dialog.
        /// </summary>
        public static string FirstRunTask_Description {
            get {
                return ResourceManager.GetString("FirstRunTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Foreground Lock Timeout.
        /// </summary>
        public static string ForegroundLockTimeoutTask_Description {
            get {
                return ResourceManager.GetString("ForegroundLockTimeoutTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed successfully. Foreground lock timeout has been set to {0} milliseconds..
        /// </summary>
        public static string ForegroundLockTimeoutTask_FixedTimeout {
            get {
                return ResourceManager.GetString("ForegroundLockTimeoutTask_FixedTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground lock timeout is less than {0} milliseconds, which may occasionally cause the game to return to the desktop. Fixing....
        /// </summary>
        public static string ForegroundLockTimeoutTask_InsufficientTimeout {
            get {
                return ResourceManager.GetString("ForegroundLockTimeoutTask_InsufficientTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground lock timeout is no less than {0} milliseconds. No action required..
        /// </summary>
        public static string ForegroundLockTimeoutTask_SufficientTimeout {
            get {
                return ResourceManager.GetString("ForegroundLockTimeoutTask_SufficientTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is setting compatibility and configuring game options, and has not finished yet. Are you sure you want to abort the registry tool?.
        /// </summary>
        public static string MainWindow_Closing_Warning_Message {
            get {
                return ResourceManager.GetString("MainWindow_Closing_Warning_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MainWindow_Closing_Warning_Title {
            get {
                return ResourceManager.GetString("MainWindow_Closing_Warning_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View on GitHub.
        /// </summary>
        public static string MainWindow_GitHubUrlButton {
            get {
                return ResourceManager.GetString("MainWindow_GitHubUrlButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  messages.
        /// </summary>
        public static string MainWindow_MessagesCount {
            get {
                return ResourceManager.GetString("MainWindow_MessagesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may not be in the game directory. Please ensure that the files of {0} are copied to the game directory before running. File {1} not found..
        /// </summary>
        public static string MainWindow_Not_In_Game_Directory_Message {
            get {
                return ResourceManager.GetString("MainWindow_Not_In_Game_Directory_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MainWindow_Not_In_Game_Directory_Title {
            get {
                return ResourceManager.GetString("MainWindow_Not_In_Game_Directory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} [ Remaining Tasks: {1} ].
        /// </summary>
        public static string MainWindow_Title_With_Wait_Count {
            get {
                return ResourceManager.GetString("MainWindow_Title_With_Wait_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Network Environment.
        /// </summary>
        public static string NetworkInterfaceTask_Description {
            get {
                return ResourceManager.GetString("NetworkInterfaceTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your computer has multiple network cards, as listed below. You may not be able to see other players in the LAN lobby. To avoid this problem, temporarily disable other network cards when connecting to the LAN, and keep only the network card connected to the LAN.{0}.
        /// </summary>
        public static string NetworkInterfaceTask_MultipleNetworkCards {
            get {
                return ResourceManager.GetString("NetworkInterfaceTask_MultipleNetworkCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Game Path Format.
        /// </summary>
        public static string PathCheckTask_Description {
            get {
                return ResourceManager.GetString("PathCheckTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current game directory path contains the special character % (percent sign). Windows Firewall may not handle this correctly..
        /// </summary>
        public static string PathCheckTask_PathContainsPercent {
            get {
                return ResourceManager.GetString("PathCheckTask_PathContainsPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current game directory path is too long. The game may not run normally..
        /// </summary>
        public static string PathCheckTask_PathTooLong {
            get {
                return ResourceManager.GetString("PathCheckTask_PathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory image virtualization (mandatory ASLR) is disabled by default..
        /// </summary>
        public static string ProcessMitigationTask_AslrDefaultOff {
            get {
                return ResourceManager.GetString("ProcessMitigationTask_AslrDefaultOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory image virtualization (mandatory ASLR) is enabled by default, and disabling it for {0} failed. This may cause Ares to fail to start normally. Please find and disable the &quot;Force Image Virtualization (Mandatory ASLR)&quot; option in the &quot;System settings&quot; tab under &quot;Windows Security Center&quot; → &quot;App &amp; browser control&quot;, or disable this option individually for the game file in the &quot;Program settings&quot; tab..
        /// </summary>
        public static string ProcessMitigationTask_AslrDefaultOnFailedToDisable {
            get {
                return ResourceManager.GetString("ProcessMitigationTask_AslrDefaultOnFailedToDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory image virtualization (mandatory ASLR) is enabled by default, but it has been successfully disabled for {0}..
        /// </summary>
        public static string ProcessMitigationTask_AslrDefaultOnSuccessfullyDisabled {
            get {
                return ResourceManager.GetString("ProcessMitigationTask_AslrDefaultOnSuccessfullyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable Mandatory Image Virtualization.
        /// </summary>
        public static string ProcessMitigationTask_Description {
            get {
                return ResourceManager.GetString("ProcessMitigationTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized boolean value {0}. Unable to determine option status..
        /// </summary>
        public static string ProcessMitigationTask_UnrecognizedBoolean {
            get {
                return ResourceManager.GetString("ProcessMitigationTask_UnrecognizedBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution complete. Please read the warnings and errors in dark red carefully before closing this window..
        /// </summary>
        public static string Program_Execution_Complete_Message {
            get {
                return ResourceManager.GetString("Program_Execution_Complete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution Complete.
        /// </summary>
        public static string Program_Execution_Complete_Title {
            get {
                return ResourceManager.GetString("Program_Execution_Complete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QRes check failed. {0}When not using a renderer patch or using an outdated renderer patch, running the game in windowed mode may cause issues. It is recommended to update the qres.dat program or use a modern renderer patch whenever possible..
        /// </summary>
        public static string QResTask_CheckFailed {
            get {
                return ResourceManager.GetString("QResTask_CheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check QRes High DPI Scaling Issue.
        /// </summary>
        public static string QResTask_Description {
            get {
                return ResourceManager.GetString("QResTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpatched QRes detected. When not using a renderer patch or using an outdated renderer patch, running the game in windowed mode on a high-DPI monitor may result in resolution errors or the error message &quot;Screen mode not found&quot;. It is recommended to update the qres.dat program or use a modern renderer patch whenever possible..
        /// </summary>
        public static string QResTask_UnfixedQRes {
            get {
                return ResourceManager.GetString("QResTask_UnfixedQRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowfish.dll file not found..
        /// </summary>
        public static string Ra2RegTask_BlowfishNotFound {
            get {
                return ResourceManager.GetString("Ra2RegTask_BlowfishNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need to register Blowfish.dll..
        /// </summary>
        public static string Ra2RegTask_BlowfishNotRequired {
            get {
                return ResourceManager.GetString("Ra2RegTask_BlowfishNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blowfish.dll registered successfully..
        /// </summary>
        public static string Ra2RegTask_BlowfishRegistered {
            get {
                return ResourceManager.GetString("Ra2RegTask_BlowfishRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Red Alert 2.
        /// </summary>
        public static string Ra2RegTask_Description {
            get {
                return ResourceManager.GetString("Ra2RegTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry write successful..
        /// </summary>
        public static string Ra2RegTask_RegistryWriteSuccess {
            get {
                return ResourceManager.GetString("Ra2RegTask_RegistryWriteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Obsolete Files.
        /// </summary>
        public static string RemoveObsoleteFilesTask_Description {
            get {
                return ResourceManager.GetString("RemoveObsoleteFilesTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem encountered while deploying renderer patch. {0}.
        /// </summary>
        public static string RendererTask_DeploymentError {
            get {
                return ResourceManager.GetString("RendererTask_DeploymentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Renderer Patch.
        /// </summary>
        public static string RendererTask_Description {
            get {
                return ResourceManager.GetString("RendererTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: If needed, renderer patch settings can be changed from within the {0} client.
        ///It is recommended to always use a modern renderer patch on Windows 8/10/11, such as TS-DDraw or CnC-DDraw..
        /// </summary>
        public static string RendererTask_Hint {
            get {
                return ResourceManager.GetString("RendererTask_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not setting renderer patch..
        /// </summary>
        public static string RendererTask_NoRenderer {
            get {
                return ResourceManager.GetString("RendererTask_NoRenderer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting renderer patch to CnC-DDraw..
        /// </summary>
        public static string RendererTask_SetToCnCDDraw {
            get {
                return ResourceManager.GetString("RendererTask_SetToCnCDDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Resolution.
        /// </summary>
        public static string ResolutionTask_Description {
            get {
                return ResourceManager.GetString("ResolutionTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop resolution detected: {0}×{1}..
        /// </summary>
        public static string ResolutionTask_DesktopResolution {
            get {
                return ResourceManager.GetString("ResolutionTask_DesktopResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game resolution set to {0}×{1}..
        /// </summary>
        public static string ResolutionTask_SetGameResolution {
            get {
                return ResourceManager.GetString("ResolutionTask_SetGameResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Runtime Components.
        /// </summary>
        public static string RuntimeComponentTask_Description {
            get {
                return ResourceManager.GetString("RuntimeComponentTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework {0} is installed..
        /// </summary>
        public static string RuntimeComponentTask_DotNet4Installed {
            get {
                return ResourceManager.GetString("RuntimeComponentTask_DotNet4Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .NET Framework 4 is not installed..
        /// </summary>
        public static string RuntimeComponentTask_DotNet4NotInstalled {
            get {
                return ResourceManager.GetString("RuntimeComponentTask_DotNet4NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current .NET Framework 4 version is lower than 4.8..
        /// </summary>
        public static string RuntimeComponentTask_DotNet4VersionTooLow {
            get {
                return ResourceManager.GetString("RuntimeComponentTask_DotNet4VersionTooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNA Framework 4.0 is installed..
        /// </summary>
        public static string RuntimeComponentTask_Xna4Installed {
            get {
                return ResourceManager.GetString("RuntimeComponentTask_Xna4Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNA Framework 4.0 is not installed..
        /// </summary>
        public static string RuntimeComponentTask_Xna4NotInstalled {
            get {
                return ResourceManager.GetString("RuntimeComponentTask_Xna4NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} audio output device(s)..
        /// </summary>
        public static string SpeakerNumTask_AudioDevicesFound {
            get {
                return ResourceManager.GetString("SpeakerNumTask_AudioDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Audio Output Devices.
        /// </summary>
        public static string SpeakerNumTask_Description {
            get {
                return ResourceManager.GetString("SpeakerNumTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No audio output device exists on the current system. Please connect headphones or speakers before entering the game, otherwise the game may crash..
        /// </summary>
        public static string SpeakerNumTask_NoAudioDevice {
            get {
                return ResourceManager.GetString("SpeakerNumTask_NoAudioDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows version is too low. This feature is not available..
        /// </summary>
        public static string Task_OsVersionTooLow_NoFeature {
            get {
                return ResourceManager.GetString("Task_OsVersionTooLow_NoFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process returned exit code {0}. Execution failed..
        /// </summary>
        public static string Task_ProcessExitCodeFailure {
            get {
                return ResourceManager.GetString("Task_ProcessExitCodeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution complete..
        /// </summary>
        public static string TaskManager_ExecutionComplete {
            get {
                return ResourceManager.GetString("TaskManager_ExecutionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution failed: {0}.
        /// </summary>
        public static string TaskManager_ExecutionFailed {
            get {
                return ResourceManager.GetString("TaskManager_ExecutionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Game Username.
        /// </summary>
        public static string UserNameTask_Description {
            get {
                return ResourceManager.GetString("UserNameTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The current player nickname &quot;{0}&quot; contains non-ASCII characters. If the player nickname contains no ASCII characters at all, engines such as Ares 3.0 will crash..
        /// </summary>
        public static string UserNameTask_NonAsciiUsername {
            get {
                return ResourceManager.GetString("UserNameTask_NonAsciiUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting player nickname to &quot;{0}&quot;..
        /// </summary>
        public static string UserNameTask_SetUsername {
            get {
                return ResourceManager.GetString("UserNameTask_SetUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Xbox Game Bar.
        /// </summary>
        public static string XboxGameBarTask_Description {
            get {
                return ResourceManager.GetString("XboxGameBarTask_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Bar is enabled, which may cause certain areas of the game to be unclickable on some computers with certain renderer patches. Please find the relevant setting under Start Menu → Settings → Gaming → Xbox Game Bar and disable the game bar..
        /// </summary>
        public static string XboxGameBarTask_GameBarEnabled {
            get {
                return ResourceManager.GetString("XboxGameBarTask_GameBarEnabled", resourceCulture);
            }
        }
    }
}
