name: Build Mo3RegUI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore Packages
      run: nuget restore

    - name: Build
      run: msbuild /t:Clean,Build /p:Configuration=Release /p:platform="Any CPU" /p:TargetFramework=net40

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mo3RegUI
        path: Mo3RegUI/bin/Release/Mo3RegUI.exe
        if-no-files-found: error
